//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudentAcademicAdvisory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicInformation
    {
        public int Id { get; set; }
        public int AcademicInstitutionId { get; set; }
        public int EducationLevelId { get; set; }
        public System.DateTime GaduationYear { get; set; }
        public int InstructorId { get; set; }
        public int FieldOfStudiesId { get; set; }
    
        public virtual AcademicInstution AcademicInstution { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual FieldOfStudy FieldOfStudy { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
