//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudentAcademicAdvisory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvisorDocument
    {
        public int Id { get; set; }
        public int ProjectAdvisorId { get; set; }
        public string DocumentTitle { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string Message { get; set; }
        public string Attachement { get; set; }
    
        public virtual FinalProjectAdvisor FinalProjectAdvisor { get; set; }
    }
}
