//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudentAcademicAdvisory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinalProject()
        {
            this.FinalProjectAdvisors = new HashSet<FinalProjectAdvisor>();
            this.FinalProjectStudents = new HashSet<FinalProjectStudent>();
            this.SelectedAdvisors = new HashSet<SelectedAdvisor>();
        }
    
        public int Id { get; set; }
        public string ProjectTitle { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> NoOfStudents { get; set; }
        public bool IsTerminated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalProjectAdvisor> FinalProjectAdvisors { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalProjectStudent> FinalProjectStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedAdvisor> SelectedAdvisors { get; set; }
    }
}
