//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudentAcademicAdvisory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstractorRole
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int InstractorId { get; set; }
        public bool IsOnPosition { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Role Role { get; set; }
    }
}
