//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStudentAcademicAdvisory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OSAAEntities : DbContext
    {
        public OSAAEntities()
            : base("name=OSAAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicInformation> AcademicInformations { get; set; }
        public virtual DbSet<AcademicInstution> AcademicInstutions { get; set; }
        public virtual DbSet<ActiveInstructor> ActiveInstructors { get; set; }
        public virtual DbSet<AdmissionType> AdmissionTypes { get; set; }
        public virtual DbSet<AdvisorDocument> AdvisorDocuments { get; set; }
        public virtual DbSet<AdvisorType> AdvisorTypes { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EducationLevel> EducationLevels { get; set; }
        public virtual DbSet<FieldOfStudy> FieldOfStudies { get; set; }
        public virtual DbSet<FinalProjectAdvisor> FinalProjectAdvisors { get; set; }
        public virtual DbSet<FinalProject> FinalProjects { get; set; }
        public virtual DbSet<FinalProjectStudent> FinalProjectStudents { get; set; }
        public virtual DbSet<InstractorRole> InstractorRoles { get; set; }
        public virtual DbSet<InstructorFeedback> InstructorFeedbacks { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SelectedAdvisor> SelectedAdvisors { get; set; }
        public virtual DbSet<StudentBatch> StudentBatches { get; set; }
        public virtual DbSet<StudentDocument> StudentDocuments { get; set; }
        public virtual DbSet<StudentFeedback> StudentFeedbacks { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SystemAdministratorInformation> SystemAdministratorInformations { get; set; }
        public virtual DbSet<SystemAdmin> SystemAdmins { get; set; }
        public virtual DbSet<InstructorImage> InstructorImages { get; set; }
        public virtual DbSet<StudentImage> StudentImages { get; set; }
        public virtual DbSet<SystemAdminImage> SystemAdminImages { get; set; }
    }
}
